"use client";

// Figma "option 11" (node 503:2) — the home page's default background,
// always visible behind the 3D flower (mounted before <Spline> in
// FlowerScene, no z-index, so normal paint order puts Spline's canvas on
// top of it, same as HoverFigTreeVisual/HoverRadioVisual). Unlike those two,
// this one isn't opacity-toggled by a hover state — it just always shows
// through wherever the flower doesn't occlude it, and gets covered over
// whenever a hover overlay's own opaque bg-black is active.
//
// The 4 "musician designer experimenter artist" lines are generated by
// repeating that 4-word cycle far more times than any real viewport could
// fit, then centering a much-wider-than-viewport row (300vw) — so both
// ends always run off-screen no matter the window's width, rather than
// hard-coding a pixel crop for one specific canvas size like the Figma
// source does.
const WORD_CYCLE = ["musician", "designer", "experimenter", "artist"];
const REPEAT_COUNT = 40;
const REPEATED_WORDS = Array.from({ length: REPEAT_COUNT }, (_, i) => WORD_CYCLE[i % WORD_CYCLE.length]);

const LINES: { highlight: string }[] = [
  { highlight: "designer" },
  { highlight: "artist" },
  { highlight: "experimenter" },
  { highlight: "musician" },
];

function RepeatingLine({ highlight }: { highlight: string }) {
  return (
    <p className="font-sans whitespace-nowrap text-white" style={{ fontSize: "3.8vw", letterSpacing: "-0.09vw", lineHeight: 1 }}>
      {REPEATED_WORDS.map((word, i) => (
        <span key={i} style={{ opacity: word === highlight ? 1 : 0.6 }}>
          {word}
          {i < REPEATED_WORDS.length - 1 ? " " : ""}
        </span>
      ))}
    </p>
  );
}

export function HomeBackground() {
  return (
    <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden" data-name="home-background">
      <div className="absolute left-1/2 top-[4vh] -translate-x-1/2 text-center">
        <p
          className="font-karla whitespace-nowrap font-bold uppercase text-white"
          style={{ fontSize: "7.6vw", letterSpacing: "0.4vw", lineHeight: 0.5 }}
        >
          HANNAH SHIN
        </p>
        <div
          className="font-mono mt-[2vw] flex items-center justify-center gap-[6vw] uppercase text-white"
          style={{ fontSize: "1.6vw" }}
        >
          <span>CS + VISUAL MEDIA</span>
          <span>@ DUKE UNIVERSITY</span>
        </div>
      </div>

      <div className="absolute left-1/2 top-[62vh] flex -translate-x-1/2 flex-col" style={{ gap: "0.3vw", width: "300vw" }}>
        {LINES.map(({ highlight }) => (
          <RepeatingLine key={highlight} highlight={highlight} />
        ))}
      </div>
    </div>
  );
}
